<?php

/**
 * @file
 * Primary module hooks for OpenCulturas faq module.
 */

declare(strict_types = 1);

use Drupal\node\NodeInterface;
use Drupal\taxonomy\Entity\Term;
use Drupal\taxonomy\TermInterface;

/**
 * Implements hook_ENTITY_TYPE_prepare_form().
 */
function openculturas_faq_node_prepare_form(NodeInterface $node): void {
  $is_new_entity = $node->bundle() === 'faq' && $node->isNew();
  if ($is_new_entity === FALSE) {
    return;
  }

  $request = \Drupal::request();
  if ($request->query->has('field_faq_category')) {
    $faq_category_id = $request->get('field_faq_category');
    if (empty($faq_category_id)) {
      return;
    }

    $faq_category = Term::load($faq_category_id);
    if (!$faq_category instanceof TermInterface) {
      return;
    }

    if ($faq_category->bundle() !== 'faq_category') {
      return;
    }

    $node->set('field_faq_category', ['target_id' => $faq_category->id()]);
  }
}
