<?php

/**
 * @file
 * Primary module hooks for OpenCulturas OpenstreetMap module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\openculturas_openstreetmap\OpenStreetMap\ApiClient;

/**
 * Implements hook_help().
 */
function openculturas_openstreetmap_help(string $route_name, RouteMatchInterface $route_match): null|string {
  if ($route_name === 'openculturas_openstreetmap.settings') {
    return '<p>' . t("The settings require a little off-platform preparation, please read the <a href='@help-url'>help page</a> for instructions.", [
      '@help-url' => Url::fromRoute('help.page', ['name' => 'openculturas_openstreetmap'])->toString(),
    ]) . '</p>';
  }

  if ($route_name === 'help.page.openculturas_openstreetmap') {
    $output = '<h2>' . t('Getting started with OpenStreetMap in OpenCulturas') . '</h2>';
    $output .= '<h3>' . t('Production API') . '</h3>';
    $output .= '<p>' . t('<strong>Important:</strong> With these settings your users (with a privileged role) can change information on OpenStreetMap.org. When you are not sure about the effect, try the Development API first.') . '</p>';
    $output .= '<p>' . t('Required: an OpenStreetMap account and a connected OAuth2 app. It is good practise to create an account for your platform rather than using an existing personal account.') . '</p>';
    $output .= '<ol>';
    $output .= '<li>' . t('Create an account at <a href="@osm_url">@osm_url</a>', [
      '@osm_url' => ApiClient::ENDPOINT,
    ]) . '</li>';
    $output .= '<li>' . t('Add an <a href="@oauth2_app_url">OAuth2 app</a> with the redirect uri <code>@redirect_url</code> and at least with the scope: <em>Modify the map (allow_write_api)</em>', [
      '@oauth2_app_url' => ApiClient::ENDPOINT . '/oauth2/applications',
      '@redirect_url' => Url::fromRoute('oauth2_client.code', ['plugin' => 'openstreetmap'], ['absolute' => TRUE])->toString(),
    ]) . '</li>';
    $output .= '<li>' . t('The provided client ID and secret need to be stored safely. Therefore create a file in the private file system (@file_path) with content <code>{"client_id": "CLIENT-ID","client_secret": "CLIENT_SECRET"}</code>.', [
      '@file_path' => 'private://osm/secret.json',
    ]) . '</li>';
    $output .= '<li>' . t('<a href="@enable_url">Enable the OAuth2 Client</a> and <a href="@edit_url">request a token</a>.', [
      '@enable_url' => Url::fromRoute('entity.oauth2_client.enable', ['oauth2_client' => 'openstreetmap'])->toString(),
      '@edit_url' => Url::fromRoute('entity.oauth2_client.edit_form', ['oauth2_client' => 'openstreetmap'])->toString(),
    ]) . '</li>';
    $output .= '</ol>';
    $output .= '<p>' . t('<strong>Please note:</strong> Do not switch the UI language until you have requested your token. A different language prefix in the URL will lead to failure.') . '</p>';
    $output .= '<h3>' . t('Development API') . '</h3>';
    $output .= '<p>' . t('The OSM community provides a development setup for testing purposes. Neither accounts nor data are synchronized with the official OpenStreetMap, therefore it requires a separate account.') . '</p>';
    $output .= '<ol>';
    $output .= '<li>' . t('Create an account at <a href="@osm_url">@osm_url</a>', [
      '@osm_url' => ApiClient::DEV_ENDPOINT,
    ]) . '</li>';
    $output .= '<li>' . t('Add an <a href="@oauth2_app_url">OAuth2 app</a> with the redirect uri <code>@redirect_url</code> and at least with scope: <em>Modify the map (allow_write_api)</em>', [
      '@oauth2_app_url' => ApiClient::DEV_ENDPOINT . '/oauth2/applications',
      '@redirect_url' => Url::fromRoute('oauth2_client.code', ['plugin' => 'openstreetmap_dev'], ['absolute' => TRUE])->toString(),
    ]) . '</li>';
    $output .= '<li>' . t('Store the id and secret safely in (@file_path) with the content <code>{"client_id": "CLIENT-ID","client_secret": "CLIENT_SECRET"}</code>.', [
      '@file_path' => 'private://osm/secret_dev.json',
    ]) . '</li>';
    $output .= '<li>' . t('<a href="@enable_url">Enable the OAuth2 Client</a> and <a href="@edit_url">request a token</a>.', [
      '@enable_url' => Url::fromRoute('entity.oauth2_client.enable', ['oauth2_client' => 'openstreetmap_dev'])->toString(),
      '@edit_url' => Url::fromRoute('entity.oauth2_client.edit_form', ['oauth2_client' => 'openstreetmap_dev'])->toString(),
    ]) . '</li>';
    $output .= '<li>' . t('Create a test location on <a href="@osm_url">@osm_url</a> and copy the ID', [
      '@osm_url' => ApiClient::DEV_ENDPOINT,
      '@redirect_url' => Url::fromRoute('oauth2_client.code', ['plugin' => 'openstreetmap_dev'], ['absolute' => TRUE])->toString(),
    ]) . '</li>';
    $output .= '<li>' . t('Make sure the Development mode is enabled and paste your test locationʼs ID in the OSM ID field') . '</li>';
    $output .= '</ol>';
    $output .= '<p>' . t('<strong>Please note:</strong> In any case the “Finder” uses the public OpenStreetMap data. A test location with a makeshift name will likely not be found (or not where you expect it). It is recommended to create an existing location as a test node.') . '</p>';
    $output .= '<h3>' . t('Boundaries') . '</h3>';
    $output .= '<p>' . t('We use <a href="https://photon.komoot.io">https://photon.komoot.io</a> to find the location in the wizard. By default it would search worldwide. To limit the result list we set the boundaries for the search area. You can select from pre-defined areas or define a custom area.') . '</p>';
    $output .= '<p>' . t('To create a custom area') . '</p>';
    $output .= '<ol>';
    $output .= '<li>' . t('Go to <a href="https://boundingbox.klokantech.com">https://boundingbox.klokantech.com</a>') . '</li>';
    $output .= '<li>' . t('Use the search field to find the country/state, it should set the bounds automatically. Alternatively drag and resize the box to create a custom area.') . '</li>';
    $output .= '<li>' . t('Select <em>CSV</em> in the "Copy & Paste" field (in bottom left corner). The order is West, South, East, North') . '</li>';
    $output .= '<li>' . t('On the settings page, select <em>Custom</em> in the Area field and paste the values accordingly.') . '</li>';
    return $output . '</ol>';
  }

  return NULL;
}
