<?php

declare(strict_types=1);

/**
 * Implements hook_views_data_alter().
 */
function geofield_proximity_filter_extra_views_data_alter(array &$data) {
  $data['views']['geofield_proximity_filter_extra_combine'] = [
    'title' => t('Geofield proximity_filter'),
    'help' => t('Combine multiple fields together and search by them.'),
    'filter' => [
      'id' => 'geofield_proximity_filter_extra_combine',
    ],
  ];
}
