import process from 'node:process';
// eslint-disable-next-line import/no-extraneous-dependencies
import chalk from 'chalk';
// eslint-disable-next-line import/no-extraneous-dependencies
import { transformFile } from '@babel/core/lib/transform-file';
import log from './log';

export default function compile(filePath, callback) {
  // Transform the file.
  // Check process.env.NODE_ENV to see if we should create sourcemaps.
  transformFile(
    filePath,
    {
      sourceMaps: process.env.NODE_ENV === 'development' ? 'inline' : false,
      comments: false,
      plugins: [
        [
          'add-header-comment',
          {
            header: [
              `DO NOT EDIT THIS FILE.\nSee the following change record for more information,\nhttps://www.drupal.org/node/2815083\n@preserve`,
            ],
          },
        ],
      ],
    },
    (err, result) => {
      if (err) {
        log(chalk.red(err));
        process.exitCode = 1;
      } else {
        callback(result.code);
      }
    },
  );
}
