<?php

/**
 * @file
 * Install, update and uninstall functions for the cookies_popover module.
 */

declare(strict_types=1);

use Drupal\Core\Field\FieldConfigInterface;
use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_install().
 */
function cookies_popover_install(bool $is_syncing): void {
  if ($is_syncing) {
    return;
  }

  /** @var \Drupal\Core\Field\FieldConfigInterface|null $field */
  $field = FieldConfig::loadByName('paragraph', 'block', 'field_block_ref');
  if ($field instanceof FieldConfigInterface) {
    $selection_settings = $field->getSetting('selection_settings');
    if (is_array($selection_settings) && $field->getSetting('selection') === 'categories') {
      $selection_settings['categories']['Cookies Popover'] = 'Cookies Popover';
    }
    elseif (is_array($selection_settings) && $field->getSetting('selection') === 'blocks') {
      $selection_settings['plugin_ids']['cookies_settings_button'] = 'cookies_settings_button';
    }

    $field->setSetting('selection_settings', $selection_settings);
    $field->save();
  }
}

/**
 * Implements hook_uninstall().
 */
function cookies_popover_uninstall(bool $is_syncing): void {
  if ($is_syncing) {
    return;
  }

  /** @var \Drupal\Core\Field\FieldConfigInterface|null $field */
  $field = FieldConfig::loadByName('paragraph', 'block', 'field_block_ref');
  if ($field instanceof FieldConfigInterface) {
    $selection_settings = $field->getSetting('selection_settings');
    if (is_array($selection_settings) && $field->getSetting('selection') === 'categories') {
      unset($selection_settings['categories']['Cookies Popover']);
    }
    elseif (is_array($selection_settings) && $field->getSetting('selection') === 'blocks') {
      unset($selection_settings['plugin_ids']['cookies_settings_button']);
    }

    $field->setSetting('selection_settings', $selection_settings);
    $field->save();
  }
}
