/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.behaviors.leaflet_extra = {
    attach: function attach() {
      $(document).on('leafletMapInit', function (e, settings, lMap) {
        if (settings.settings.center && settings.settings.center.lat && settings.settings.center.lon) {
          var latlng = L.latLng(settings.settings.center.lat, settings.settings.center.lon);
          var circle = L.circle(latlng, {
            radius: parseInt(settings.settings.radius, 10) * 1000
          }).addTo(lMap);
          circle.fillOpacity(0.2);
          lMap.fitBounds(circle.getBounds());
          lMap.flyToBounds(circle.getBounds());
        }
      });
    }
  };
})(jQuery, Drupal);