<?php
// phpcs:ignoreFile -- this file is autogenerated.

declare(strict_types=1);

use DrupalFinder\DrupalFinder;
use DrupalRector\Set\Drupal10SetList;
use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\SetList;

return static function (RectorConfig $rectorConfig): void {
  $rectorConfig->sets([
    SetList::DEAD_CODE,
    SetList::CODE_QUALITY,
    SetList::CODING_STYLE,
    SetList::TYPE_DECLARATION,
    SetList::EARLY_RETURN,
    SetList::INSTANCEOF,
    Drupal10SetList::DRUPAL_10
  ]);

  if (getenv('CI')) {
    // Ensure file system caching is used instead of in-memory.
    $rectorConfig->cacheClass(\Rector\Caching\ValueObject\Storage\FileCacheStorage::class);

    // Specify a path that works locally as well as on CI job runners.
    $rectorConfig->cacheDirectory(__DIR__ . '/.rectorcache');
  }

  $drupalFinder = new DrupalFinder();
  $drupalFinder->locateRoot(__DIR__);
  $drupalRoot = $drupalFinder->getDrupalRoot();
  $rectorConfig->autoloadPaths([
    $drupalRoot . '/core',
    $drupalRoot . '/modules',
    $drupalRoot . '/themes'
  ]);

  $rectorConfig->fileExtensions(['php', 'module', 'theme', 'install', 'profile']);
  $rectorConfig->importNames(true, false);
  $rectorConfig->importShortClasses(false);

  $rectorConfig->paths([
    __DIR__ . '/profile/'
  ]);
  $rectorConfig->phpstanConfig(
    __DIR__ . '/phpstan-for-rector.neon'
  );
  $rectorConfig->phpVersion(
    \Rector\ValueObject\PhpVersion::PHP_81
  );

  $rectorConfig->skip([
    \Rector\DeadCode\Rector\ClassMethod\RemoveUselessParamTagRector::class,
    \Rector\DeadCode\Rector\Property\RemoveUselessVarTagRector::class,
    \Rector\DeadCode\Rector\ClassMethod\RemoveUselessReturnTagRector::class,
    \Rector\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector::class => [
      __DIR__ . '/profile/'
    ],
    __DIR__ . '/profile/modules/custom/openculturas_custom/src/Plugin/DateAugmenter/AddToCal.php',
    __DIR__ . '/profile/modules/custom/geofield_proximity_filter_extra/src/Controller/AutocompleteFiltersController.php',
    __DIR__ . '/profile/modules/custom/openculturas_faq/src/ProxyClass/OpenCulturasFaqUninstallValidator.php',
    __DIR__ . '/profile/modules/custom/openculturas_discussions/src/ProxyClass/OpenCulturasDiscussionsUninstallValidator.php',
  ]);
  $rectorConfig->parallel(maxNumberOfProcess: 2);
};
