/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal, drupalSettings) {
  Drupal.behaviors.locate_me = {
    attach: function attach(context) {
      var $buttons = $('.button--locate_me', context);

      if ($buttons.length) {
        var messages = new Drupal.Message();
        $buttons.click(function (event) {
          var $button = $(event.currentTarget);
          event.preventDefault();

          if ('geolocation' in navigator) {
            messages.clear();
            messages.add(Drupal.t('Locating...'));
            Drupal.behaviors.locate_me.target_id = $button.attr('data-target-selector-id');
            navigator.geolocation.getCurrentPosition(Drupal.behaviors.locate_me.success, Drupal.behaviors.locate_me.error, {
              timeout: 5000,
              enableHighAccuracy: true
            });
          } else {
            messages.clear();
            messages.add(Drupal.t('Geolocation is not supported by this browser.'), {
              type: 'error'
            });
          }

          return false;
        });
      }
    },
    success: function success(position) {
      var messages = new Drupal.Message();
      messages.clear();
      var latitude = position.coords.latitude;
      var longitude = position.coords.longitude;
      var baseUrl = drupalSettings.path.baseUrl;
      var providers = drupalSettings.geocode_origin_autocomplete.providers.toString();
      var geocodePath = "".concat(baseUrl, "geocoder/api/reverse_geocode");
      var latLon = encodeURIComponent("".concat(latitude, ",").concat(longitude));
      $.ajax({
        url: "".concat(geocodePath, "?latlng=").concat(latLon, "&geocoder=").concat(providers),
        type: 'GET',
        contentType: 'application/json; charset=utf-8',
        dataType: 'json'
      }).fail(function () {
        messages.clear();
        messages.add(Drupal.t('A server error has occurred.'), {
          type: 'error'
        });
      }).done(function (data) {
        var $value = data[0].formatted_address;
        var $selector = "[data-drupal-selector=".concat(Drupal.behaviors.locate_me.target_id, "]");
        var $element = $($selector);

        if ($element.length) {
          $element.val($value);
        }
      });
    },
    error: function error() {
      var messages = new Drupal.Message();
      messages.clear();
      messages.add(Drupal.t('Locating not possible.'), {
        type: 'error'
      });
    }
  };
})(jQuery, Drupal, drupalSettings);