opcult_base_settings:
  type: theme_settings
  mapping:
    background_image:
      type: mapping
      label: 'Background image settings'
      mapping:
        mode:
          type: string
        path:
          label: 'Path to background image'
          type: uri
    hero_layout:
      type: string
      label: 'Hero layout'

opcult.settings:
  type: opcult_base_settings
  label: 'OpCult theme settings'
