# Schema for the configuration files of the OpenCulturas Base theme.
openculturas_base.settings:
  type: theme_settings
  label: 'OpenCulturas Base settings'
  mapping:
    primary_color:
      type: string
      label: Primary color
