<?php

declare(strict_types = 1);

use Drupal\Core\Url;
use Drupal\openculturas_calendar_widget\Form\EmbedCodeWidget;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function openculturas_calendar_widget_theme(): array {
  return [
    'page__openculturas_calendar_widget__embed' => [
      'base hook' => 'page',
    ],
  ];
}

/**
 * Implements hook_views_pre_view().
 */
function openculturas_calendar_widget_views_pre_view(ViewExecutable $viewExecutable): void {
  $routeMatch = \Drupal::routeMatch();
  if ($routeMatch->getRouteName() !== 'openculturas_calendar_widget.embed') {
    return;
  }

  if ($viewExecutable->id() === 'related_date' && $viewExecutable->current_display === 'upcoming_dates') {
    $viewExecutable->exposed_widgets = [];
    $pager = $viewExecutable->display_handler->getOption('pager');
    $pager['type'] = 'some';
    $viewExecutable->display_handler->setOption('pager', $pager);
    $viewExecutable->setItemsPerPage(12);
    $viewExecutable->display_handler->setOption('header', []);
    $css_class = $viewExecutable->display_handler->getOption('css_class');
    $viewExecutable->display_handler->setOption('css_class', $css_class . ' calendar--embed');
  }
}

/**
 * Implements hook_views_post_build().
 */
function openculturas_calendar_widget_views_post_build(ViewExecutable $viewExecutable): void {
  $routeMatch = \Drupal::routeMatch();
  if ($routeMatch->getRouteName() === 'openculturas_calendar_widget.embed') {
    return;
  }

  if ($viewExecutable->id() === 'related_date' && $viewExecutable->current_display === 'upcoming_dates') {
    $access = (\Drupal::currentUser()->hasPermission('access openculturas_calendar_widget embed') || \Drupal::currentUser()->hasPermission('administer openculturas_calendar_widget configuration'));
    if ($access) {
      $target_uri = $viewExecutable->exposed_widgets['#action'] ?? \Drupal::request()->getRequestUri();
      $exposed_input = $viewExecutable->getExposedInput();
      $exposed_input['source_uri'] = Url::fromUserInput($target_uri)->setOption('query', $exposed_input)->setAbsolute()->toString();
      $url = Url::fromRoute('openculturas_calendar_widget.embed')
        ->setOption('query', $exposed_input)
        ->setAbsolute();
      $viewExecutable->attachment_before[] = \Drupal::formBuilder()->getForm(EmbedCodeWidget::class, $url);
    }
  }
}
