block.settings.cookies_settings_button:
  type: block_settings
  label: 'Cookie settings (reopen button)'
  mapping:
    button_text:
      type: label
      label: 'Button text'
      translatable: false
