opcult_starterkit.settings:
  type: theme_settings
  label: 'OpenCulturas Sub theme settings'
  mapping:
    background_image:
      type: mapping
      label: 'Background image settings'
      mapping:
        mode:
          type: string
        path:
          label: 'Path to background image'
          type: uri
    hero_layout:
      type: string
      label: 'Hero layout'
