workflow:
  auto_cancel:
    on_new_commit: interruptible

include:
  - project: 'devops/gitlab-ci-templates'
    ref: 3.1.13
    file:
      - 'drupal.yml'

stages:
  - ".pre"
  - validate
  - build
  - deploy
  - cronjobs
  - release
  - ".post"

variables:
  CLOUDRON_DB_SOURCE: 'gitrepo'

.composer:
  image: registry.gzevd.de/safeserver/cloudron-base/sdk/php-8.4:v7.0.224170@sha256:2c58217809b28f77f0962cce791675e0d3b8932903cb479316d8860ac5bf6e35
  stage: validate
  variables:
    COMPOSER_EXIT_ON_PATCH_FAILURE: 1
    COMPOSER_MEMORY_LIMIT: -1

.validate_rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedule'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: $CI_COMMIT_REF_PROTECTED

.validate_rules_php:
  rules:
    - !reference [.validate_rules, rules]
    - if: $CI_COMMIT_BRANCH
      changes:
        paths:
          - composer.json
          - composer.lock
          - "**/*.{php,install,module}"

composer validate:
  extends: .composer
  stage: validate
  interruptible: true
  script:
    - composer validate --ansi --check-lock
  rules:
    - !reference [.validate_rules_php, rules]

phplint:
  extends:
    - .composer
    - .validate_rules_php
  stage: validate
  interruptible: true
  script:
    - composer install --ansi --no-interaction
    - vendor/bin/parallel-lint --show-deprecated -e php,module,install,profile,theme --gitlab profile > gl-code-quality-report.json
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    when: always
    expire_in: 6 mos
    reports:
      codequality: [gl-code-quality-report.json]

🧹 PHP Coding standards (PHPCS):
  extends:
    - .composer
    - .validate_rules_php
  needs:
    - phplint
  stage: validate
  interruptible: true
  allow_failure: true
  script:
    - composer install --ansi --no-interaction
    - composer run php:cs -- --report-junit=junit.xml --report-\\Micheh\\PhpCodeSniffer\\Report\\Gitlab=phpcs-quality-report.json --report-full --report-summary --report-source || EXIT_CODE=$?
    - if [[ $EXIT_CODE == "" ]]; then echo "There are no PHPCS coding standards errors or warnings"; fi
    - echo "Exiting with EXIT_CODE=$EXIT_CODE" && exit $EXIT_CODE
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    when: always
    expire_in: 6 mos
    reports:
      codequality: [phpcs-quality-report.json]
      junit: [junit.xml]

🧹 PHP Static Analysis (phpstan) :
  extends:
    - .composer
    - .validate_rules_php
  needs:
    - phplint
  stage: validate
  interruptible: true
  script:
    - composer install --ansi --no-interaction
    - php $CI_PROJECT_DIR/vendor/bin/phpstan --configuration=phpstan.ci.neon --no-progress --error-format=junit analyze > $CI_PROJECT_DIR/junit.xml || true
    - php $CI_PROJECT_DIR/vendor/bin/phpstan --configuration=phpstan.ci.neon --no-progress --error-format=gitlab analyze > $CI_PROJECT_DIR/phpstan-quality-report.json || true
    - php $CI_PROJECT_DIR/vendor/bin/phpstan --configuration=phpstan.ci.neon --no-progress analyze || EXIT_CODE=$?
    - exit $EXIT_CODE
  cache:
    - key: phpstan
      paths:
        - .phpstancache
      when: always
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    when: always
    expire_in: 6 mos
    reports:
      codequality: [phpstan-quality-report.json]
      junit: [junit.xml]

rector dry-run:
  extends:
    - .composer
    - .validate_rules_php
  needs:
    - phplint
  stage: validate
  interruptible: true
  script:
    - composer install --ansi --no-interaction
    - vendor/bin/rector --no-progress-bar --dry-run
  cache:
    - key: rector
      paths:
        - .rectorcache
      when: always
#  artifacts:
#    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
#    when: always
#    reports:
#      codequality: [gl-code-quality-report.json]

.validate_rules_npm:
  rules:
    - !reference [.validate_rules, rules]
    - if: $CI_COMMIT_BRANCH
      changes:
        paths:
          - package.json
          - package-lock.json
          - "**/package.json"
          - "**/package-lock.json"
          - "**/*.{scss,css,js}"

.npm:
  image: registry.gzevd.de/safeserver/cloudron-base/sdk/php-8.4:v7.0.224170@sha256:2c58217809b28f77f0962cce791675e0d3b8932903cb479316d8860ac5bf6e35
  stage: validate
  extends: .validate_rules_npm
  needs:
    - phplint

.composer_npm:
  extends:
    - .composer
    - .npm

.stylelint:
  extends: .composer_npm
  stage: validate
  interruptible: true
  before_script:
    - composer install --ansi --no-interaction
    - npm ci --no-audit --prefer-offline
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    when: always
    reports:
      codequality: [gl-code-quality-report.json]
  allow_failure: true

🧹 SCSS linting (stylelint):
  extends: .stylelint
  cache:
    - key: stylelint-scss
      paths:
        - .stylelintcache
      when: always
  script:
    - npm run lint:scss -- --cache --cache-location .stylelintcache --cache-strategy content --color  --custom-formatter=@gitlab-formatters/stylelint-formatter-gitlab --output-file=$CI_PROJECT_DIR/gl-code-quality-report.json

🧹 CSS linting (stylelint):
  extends: .stylelint
  cache:
    - key: stylelint-css
      paths:
        - .stylelintcache
      when: always
  script:
    - npm run lint:css -- --cache --cache-location .stylelintcache --cache-strategy content --color  --custom-formatter=@gitlab-formatters/stylelint-formatter-gitlab --output-file=$CI_PROJECT_DIR/gl-code-quality-report.json

.eslint:
  extends: .composer_npm
  stage: validate
  interruptible: true
  allow_failure: true
  variables:
    ESLINT_CODE_QUALITY_REPORT: gl-code-quality-report.json
  before_script:
    - composer install --ansi --no-interaction
    - npm ci --no-audit --prefer-offline
  cache:
    - key: eslint
      paths:
        - .eslintcache
      when: always
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    when: always
    reports:
      codequality: [gl-code-quality-report.json]

🧹 JavaScript linting (eslint):
  extends: .eslint
  script:
    - npm run lint:js -- --cache --format gitlab .

build:artifacts:
  extends: .build:artifacts
  image: registry.gzevd.de/safeserver/cloudron-base/sdk/php-8.4:v7.0.224170@sha256:2c58217809b28f77f0962cce791675e0d3b8932903cb479316d8860ac5bf6e35

.docker_build_image:
  needs:
    - job: build:image:base
      optional: true
    - job: build:artifacts
      artifacts: true

build:image:stage:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: never
    - !reference [.only_stage_rules_manually_optional, rules]

deploy:stage:
  extends:
    - .deploy_cloudron:stage
  needs:
    - build:image:stage
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: never
    - !reference [.only_stage_rules_manually_optional, rules]

deploy:stage:remove:
  extends: .deploy_cloudron:stage:remove
  needs:
    - deploy:stage
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: never
    - !reference [.only_stage_rules_manually_optional, rules]

build:image:prelive:
  extends: .build:image:prelive

deploy:prelive:
  extends: .deploy_cloudron:prelive
  needs:
    - build:image:prelive

database:snapshot:
  extends: .pre_cloudron
  stage: cronjobs
  variables:
    APP_ENV: stage
  script:
    - bash ${DEBUG:+-o xtrace} /ci/cloudron/db_snapshot.sh
  rules:
    - if: $DB_CREATE_SNAPSHOT

test create project:
  extends: .composer
  needs: []
  script:
    - composer create-project --remove-vcs --no-interaction --ansi drupal/openculturas_project example.org
    - cd example.org
    - composer audit --locked --no-interaction --ansi --abandoned=report
    - composer update --prefer-lowest --no-interaction --ansi
  # Enable when https://www.drupal.org/project/smtp/issues/3352909 is fixed.
  #  - composer audit --locked --no-interaction --ansi
  rules:
    - if: $TEST_COMPOSER_CREATE_PROJECT
