<?php

declare(strict_types=1);

/**
 * @file
 * Primary module hooks for Swiffy Slider module.
 */

use Drupal\Core\Template\AttributeHelper;

/**
 * Implements hook_theme().
 */
function swiffy_slider_theme($existing, $type, $theme, $path): array {
  return [
    'field__swiffy_slider_entity_reference' => [
       'base hook' => 'field',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK() for field.html.twig.
 */
function swiffy_slider_theme_suggestions_field(array $variables): array {
  $suggestions = [];
  $element = $variables['element'];
  if ($element['#formatter'] === 'swiffy_slider_entity_reference') {
    $suggestions[] = 'field__' . $element['#formatter'];
  }
  return $suggestions;
}

/**
 * Implements hook_preprocess_HOOK() for field.html.twig.
 */
function swiffy_slider_preprocess_field(&$variables): void {
  $element = $variables['element'];
  if ($element['#formatter'] === 'swiffy_slider_entity_reference') {
    $variables['swiffy_slider_attributes'] = (new \Drupal\Core\Template\Attribute())->addClass('swiffy-slider');
    if (!empty($element['#swiffy_slider_attributes'])) {
      $variables['swiffy_slider_attributes'] = AttributeHelper::mergeCollections($variables['swiffy_slider_attributes'], $element['#swiffy_slider_attributes']);
    }
    $variables['attributes']['style'] = 'list-style:none';
  }
}
