views.view.locations:
  expected_config:
    display:
      default:
        display_options:
          fields:
            field_address_location:
              settings:
                dumper: addresstext
                providers:
                  openstreetmap:
                    checked: '1'
                    weight: '0'
              type: geocoder_geofield_reverse_geocode
            title:
              alter:
                text: "<a href=\"#result-{{ counter }}\">{{ title }}</a><br>\r\n{{ field_address_location }}"
          style:
            options:
              description_field: title
              grouping:
                -
                  field: field_address_location
                  rendered: true
                  rendered_strip: false
              name_field: field_address_location
              reset_map:
                position: topright
              view_mode: address_block
  update_actions:
    delete:
      display:
        default:
          display_options:
            fields:
              field_address_locality:
              field_address_location:
                settings:
                  dumper:
                  providers:
              field_address_postal_code:
            filters:
              geofield_proximity_filter_extra_combine:
            style:
              options:
                description_field: title
                grouping:
                reset_map:
                  position: topright
                view_mode: address_block
        locations_block_map:
          display_options:
            fields:
              field_address_locality:
              field_address_location:
              field_address_postal_code:
    add:
      display:
        default:
          display_options:
            filters:
              field_address_location_lat:
                admin_label: ''
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  max_placeholder: ''
                  min_placeholder: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  placeholder: ''
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: field_address_location_lat
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: field_address_location_lat
                is_grouped: false
                operator: 'not empty'
                plugin_id: numeric
                relationship: field_address_data
                table: paragraph__field_address_location
                value:
                  max: ''
                  min: ''
                  value: ''
              field_address_location_lon:
                admin_label: ''
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  max_placeholder: ''
                  min_placeholder: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  placeholder: ''
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: field_address_location_lon
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: field_address_location_lon
                is_grouped: false
                operator: 'not empty'
                plugin_id: numeric
                relationship: field_address_data
                table: paragraph__field_address_location
                value:
                  max: ''
                  min: ''
                  value: ''
            style:
              options:
                feature_properties:
                  values: ''
                geocoder:
                  settings:
                    autocomplete:
                      placeholder: 'Search Address'
                      title: 'Search an Address on the Map'
                leaflet_markercluster:
                  excluded: '0'
                leaflet_popup:
                  options: '{"maxWidth":"300","minWidth":"50","autoPan":true}'
                  value: title
                  view_mode: address_block
                leaflet_tooltip:
                  options: '{"permanent":false,"direction":"center"}'
                  value: ''
                locate:
                  automatic: false
                  control: false
                  options: '{"position":"topright","setView":"untilPanOrZoom","returnToPrevBounds":true,"keepCurrentZoomLevel":true,"strings":{"title":"Locate my position"}}'
                map_lazy_load:
                  lazy_load: false
                map_position:
                  zoomControlPosition: topleft
    change:
      display:
        default:
          display_options:
            fields:
              field_address_location:
                settings:
                  output_format: wkt
                type: geofield_latlon
              title:
                alter:
                  text: '<a href="#result-{{ counter }}">{{ title }}</a>'
            style:
              options:
                grouping: {  }
                map_scale:
                  control: false
                  options: '{"position":"bottomright","maxWidth":100,"metric":true,"imperial":false,"updateWhenIdle":false}'
                name_field: ''
                reset_map:
                  options: '{"position":"topleft","title":"Reset View"}'
