<?php

/**
 * @file
 * Install, update and uninstall functions for the openculturas_custom module.
 */

declare(strict_types=1);

use Drupal\field\Entity\FieldStorageConfig;
use Drupal\field\FieldStorageConfigInterface;

/**
 * Implements hook_update_last_removed().
 */
function openculturas_custom_update_last_removed(): int {
  return 9301;
}

/**
 * Implements hook_uninstall().
 */
function openculturas_custom_uninstall(bool $is_syncing): void {
  if ($is_syncing) {
    return;
  }

  /** @var \Drupal\field\FieldStorageConfigInterface|null $field */
  $field = FieldStorageConfig::loadByName('node', 'field_event_status');
  if ($field instanceof FieldStorageConfigInterface && $field->getSetting('allowed_values_function') === 'openculturas_custom_event_status_allowed_values_function') {
    $field->setSetting('allowed_values_function', '');
    $field->save();
  }
}

/**
 * Fix truncated paragraph style labels.
 */
function openculturas_custom_update_10001(): void {
  $configuration = \Drupal::configFactory()->getEditable('openculturas_custom.settings');
  /** @var array<string,string> $allowed_classes */
  $allowed_classes = $configuration->get('allowed_classes') ?? [];

  foreach ($allowed_classes as $class => $label) {
    if ($label === 'Slight') {
      $allowed_classes[$class] = 'Slight contrast';
    }
    elseif ($label === 'Vivid') {
      $allowed_classes[$class] = 'Vivid contrast';
    }
  }

  $configuration->set('allowed_classes', $allowed_classes)->save();
}

/**
 * Add Inverted paragraph style.
 */
function openculturas_custom_update_10002(): void {
  $configuration = \Drupal::configFactory()->getEditable('openculturas_custom.settings');
  /** @var array<string,string> $allowed_classes */
  $allowed_classes = $configuration->get('allowed_classes') ?? [];

  if (!isset($allowed_classes['inverted'])) {
    $allowed_classes['inverted'] = 'Inverted';
    $configuration->set('allowed_classes', $allowed_classes)->save();
  }
}
