<?php

declare(strict_types=1);

$labels = [];

$exlude_list = ['[node:title]'];
foreach (['entity_form_display', 'entity_view_display'] as $entity_type) {
  foreach (\Drupal::entityTypeManager()->getStorage($entity_type)->loadMultiple() as $display) {
    /** @var \Drupal\Core\Entity\Display\EntityDisplayInterface $display */
    if (in_array('field_group', $display->getThirdPartyProviders(), TRUE)) {
      $field_groups = $display->getThirdPartySettings('field_group');
      foreach ($field_groups as $field_group) {
        if (isset($field_group['label']) && ($label = trim($field_group['label'])) && !in_array($label, $exlude_list, TRUE)) {
          $labels[] = $field_group['label'];
        }
      }
    }
  }
}

$file = __FILE__;
$twigcode = <<<EOF
<?php

declare(strict_types=1);

// phpcs:ignoreFile
// Do not edit. Generated by $file;
{% for label in labels %}
t('{{label}}', [], ['context' => 'field_group_label']);
{% endfor %}

EOF;

/** @var \Drupal\Core\Template\TwigEnvironment $twig */
$twig = \Drupal::service('twig');
natsort($labels);
$content = (string) $twig->renderInline($twigcode, ['labels' => array_unique($labels)]);
file_put_contents('../profile/TranslatableFieldGroups.php', $content);
