<?php

/**
 * @file
 * Install, update and uninstall functions.
 */

declare(strict_types=1);

use Drupal\Core\Field\FieldConfigInterface;
use Drupal\field\Entity\FieldConfig;
use Drupal\layout_builder\Entity\LayoutBuilderEntityViewDisplay;
use Drupal\layout_builder\Section;
use Drupal\layout_builder\SectionComponent;
use Drupal\openculturas_discussions\InstallerHelper;
use Drupal\update_helper\ConfigName;
use Drupal\user\Entity\Role;
use Drupal\user\RoleInterface;
use Drupal\views\ViewExecutable;
use Drupal\views\Views;

/**
 * Implements hook_install().
 */
function openculturas_discussions_install(bool $is_syncing): void {
  if ($is_syncing) {
    return;
  }

  /** @var \Drupal\user\RoleInterface|null $role */
  $role = Role::load(RoleInterface::AUTHENTICATED_ID);
  if ($role instanceof RoleInterface) {
    $role->grantPermission('create comment content');
    $role->grantPermission('delete own comment content');
    $role->grantPermission('use comment transition create_new_draft');
    $role->grantPermission('use comment transition to_review');
    $role->grantPermission('use text format comment_html');
    $role->save();
  }

  /** @var \Drupal\user\RoleInterface|null $role */
  $role = Role::load('magazine_editor');
  if ($role instanceof RoleInterface) {
    $role->grantPermission('edit own comment content');
    $role->grantPermission('use comment transition publish');
    $role->grantPermission('use comment transition unpublish');
    $role->grantPermission('revert comment revisions');
    $role->grantPermission('view comment revisions');
    $role->save();
  }

  /** @var \Drupal\user\RoleInterface|null $role */
  $role = Role::load('oc_organizer');
  if ($role instanceof RoleInterface) {
    $role->grantPermission('edit own comment content');
    $role->grantPermission('use comment transition publish');
    $role->save();
  }

  /** @var \Drupal\user\RoleInterface|null $role */
  $role = Role::load('oc_admin');
  if ($role instanceof RoleInterface) {
    $role->grantPermission('edit own comment content');
    $role->grantPermission('use comment transition publish');
    $role->grantPermission('use comment transition unpublish');
    $role->save();
  }

  /** @var \Drupal\Core\Entity\EntityDisplayRepositoryInterface $entity_display */
  $entity_display = \Drupal::service('entity_display.repository');

  $bundles = ['event', 'location', 'profile', 'article'];
  foreach ($bundles as $bundle) {
    // Form displays.
    $display = $entity_display->getFormDisplay('node', $bundle, 'bulk_edit');
    if (!$display->isNew()) {
      $display->setComponent('field_comments_mode', ['weight' => 5]);
      $display->save();
    }

    $display = $entity_display->getFormDisplay('node', $bundle, 'default');
    if (!$display->isNew()) {
      $display->setComponent('field_comments_mode', ['weight' => 1]);
      $settings = $display->getThirdPartySetting('field_group', 'group_administrative');
      if (is_array($settings)) {
        $settings['children'][] = 'field_comments_mode';
        $settings['children'] = array_values($settings['children']);
        $display->setThirdPartySetting('field_group', 'group_administrative', $settings);
      }

      $display->save();
    }

    // View displays.
    $display = $entity_display->getViewDisplay('node', $bundle, 'full');
    if (!$display->isNew()) {
      if ($display instanceof LayoutBuilderEntityViewDisplay && $display->isLayoutBuilderEnabled()) {
        /** @var \Drupal\Core\Field\FormatterPluginManager $formatterManager */
        $formatterManager = \Drupal::service('plugin.manager.field.formatter');
        $formatterSettings = $formatterManager->getDefaultSettings('viewfield_default');
        $formatterSettings['always_build_output'] = TRUE;
        /** @var \Drupal\Core\Block\BlockManagerInterface $blockManager */
        $blockManager = \Drupal::service('plugin.manager.block');
        /** @var \Drupal\layout_builder\Plugin\Block\FieldBlock $fieldBlock */
        $fieldBlock = $blockManager->createInstance(sprintf('field_block:node:%s:field_comments', $bundle), [
          'label' => 'Comments',
          'label_display' => 'visible',
        ]);
        $fieldBlockConf = $fieldBlock->getConfiguration();
        $fieldBlockConf['formatter']['settings'] = $formatterSettings;
        $fieldBlockConf['formatter']['label'] = 'hidden';
        $fieldBlockConf['context_mapping'] = ['entity' => 'layout_builder.entity', 'view_mode' => 'view_mode'];
        $component_field_comments = new SectionComponent(
          uuid: '48b3e6a3-abb8-452d-8695-1e980c92c4fb',
          region: 'first',
          configuration: $fieldBlockConf,
          additional: [
            'component_attributes' => [
              'block_attributes' => [
                'id' => '',
                'class' => 'intro-inline',
                'style' => '',
                'data' => '',
              ],
              'block_title_attributes' => [
                'id' => '',
                'class' => '',
                'style' => '',
                'data' => '',
              ],
              'block_content_attributes' => [
                'id' => '',
                'class' => '',
                'style' => '',
                'data' => '',
              ],
            ],
          ]
        );
        if ($bundle === 'article') {
          $component_field_comments->set('uuid', '48b3e6a3-abb8-452d-8695-1e980c92c4fb');
          $layout_settings = [
            'label' => 'Comments',
            'layout_custom_classes' => 'section-with-background comments--section',
            'layout_id' => 'comments',
          ];
          $display->appendSection(new Section('layout_oc1col_section', $layout_settings, [$component_field_comments]));
        }
        // @todo refactor this.
        elseif ($bundle === 'event') {
          $component_field_comments->set('uuid', 'cd25b039-9b4d-4077-9056-9d04a9c6c73b');
          /** @var array{block_attributes: array} $component_attributes */
          $component_attributes = $component_field_comments->get('component_attributes');
          $component_attributes['block_attributes']['id'] = 'comments';
          $component_attributes['block_attributes']['class'] = '';
          $component_field_comments->set('component_attributes', $component_attributes);
          foreach ($display->getSections() as $section) {
            foreach ($section->getComponents() as $component) {
              if ($component->getUuid() === 'd698f54f-5120-4086-8200-7eafa66a43dc') {
                $component_field_comments->setRegion($component->getRegion());
                $section->insertAfterComponent($component->getUuid(), $component_field_comments);
                break 2;
              }
            }
          }
        }
        elseif ($bundle === 'location') {
          $component_field_comments->set('uuid', 'bf779167-96df-4a78-bcc9-5bfc3bf96046');
          /** @var array{block_attributes: array} $component_attributes */
          $component_attributes = $component_field_comments->get('component_attributes');
          $component_attributes['block_attributes']['id'] = 'comments';
          $component_attributes['block_attributes']['class'] = '';
          $component_field_comments->set('component_attributes', $component_attributes);
          foreach ($display->getSections() as $section) {
            foreach ($section->getComponents() as $component) {
              if ($component->getUuid() === '52b11a81-dab1-4e9e-ad1d-e5c5dbbf6c21') {
                $component_field_comments->setRegion($component->getRegion());
                $section->insertAfterComponent($component->getUuid(), $component_field_comments);
                break 2;
              }
            }
          }
        }
        elseif ($bundle === 'profile') {
          $component_field_comments->set('uuid', 'a1d4f59b-2c94-432e-89c9-69bc90cb61af');
          /** @var array{block_attributes: array} $component_attributes */
          $component_attributes = $component_field_comments->get('component_attributes');
          $component_attributes['block_attributes']['id'] = 'comments';
          $component_attributes['block_attributes']['class'] = '';
          $component_field_comments->set('component_attributes', $component_attributes);
          foreach ($display->getSections() as $section) {
            foreach ($section->getComponents() as $component) {
              if ($component->getUuid() === '3dbd98a3-b45d-4d01-ba14-d8a671496ddd') {
                $component_field_comments->setRegion($component->getRegion());
                $section->insertAfterComponent($component->getUuid(), $component_field_comments);
                break 2;
              }
            }
          }
        }
      }
      else {
        $display->setComponent('field_comments', ['weight' => 1, 'label' => 'hidden', 'settings' => ['always_build_output' => TRUE]]);
        $display->setThirdPartySetting('field_group', 'group_comments', [
          'label' => 'Comments',
          'children' => ['field_comments'],
          'format_type' => 'details',
          'parent_name' => '',
          'region' => 'content',
          'weight' => $display->getHighestWeight() + 1,
          'format_settings' => [
            'classes' => 'comments',
            'id' => 'comments',
            'show_empty_fields' => FALSE,
            'open' => TRUE,
            'required_fields' => FALSE,
            'description' => '',
          ],
        ]);
      }

      $display->save();
    }
  }

  $view = Views::getView('moderated_content');
  if ($view instanceof ViewExecutable) {
    $type_filter_configuration = $view->getHandler('default', 'filter', 'type');
    if (is_array($type_filter_configuration)) {
      $type_filter_configuration['exposed'] = FALSE;
      $type_filter_configuration['operator'] = 'not in';
      $type_filter_configuration['value'] = ['comment' => 'comment'];
      $view->setHandler('default', 'filter', 'type', $type_filter_configuration);
      $view->save();
    }
  }

  /** @var \Drupal\Core\Field\FieldConfigInterface|null $field */
  $field = FieldConfig::loadByName('paragraph', 'view', 'field_view');
  if ($field instanceof FieldConfigInterface) {
    $allowed_views_setting = is_array($field->getSetting('allowed_views')) ? $field->getSetting('allowed_views') : [];
    $allowed_views_setting['related_comments'] = 'related_comments';
    ksort($allowed_views_setting);
    $field->setSetting('allowed_views', $allowed_views_setting);
    $field->save();
  }

  InstallerHelper::install();
}

/**
 * Implements hook_uninstall().
 */
function openculturas_discussions_uninstall(bool $is_syncing): void {
  if ($is_syncing) {
    return;
  }

  $view = Views::getView('moderated_content');
  if ($view instanceof ViewExecutable) {
    $type_filter_configuration = $view->getHandler('default', 'filter', 'type');
    if (is_array($type_filter_configuration)) {
      $type_filter_configuration['exposed'] = TRUE;
      $type_filter_configuration['operator'] = 'in';
      $type_filter_configuration['value'] = [];
      $view->setHandler('default', 'filter', 'type', $type_filter_configuration);
      $view->save();
    }
  }

  $view = Views::getView('entity_reference_node');
  if ($view instanceof ViewExecutable) {
    $type_filter_configuration = $view->getHandler('er_node_references', 'filter', 'type');
    if (is_array($type_filter_configuration)) {
      unset($type_filter_configuration['value']['comment']);
      if (isset($type_filter_configuration['value']) && count($type_filter_configuration['value']) > 0) {
        $view->setHandler('er_node_references', 'filter', 'type', $type_filter_configuration);
      }
      else {
        $view->removeHandler('er_node_references', 'filter', 'type');
      }

      $view->save();
    }
  }

  /** @var \Drupal\Core\Field\FieldConfigInterface|null $field */
  $field = FieldConfig::loadByName('paragraph', 'view', 'field_view');
  if ($field instanceof FieldConfigInterface) {
    $allowed_views_setting = is_array($field->getSetting('allowed_views')) ? $field->getSetting('allowed_views') : [];
    unset($allowed_views_setting['related_comments']);
    $field->setSetting('allowed_views', $allowed_views_setting);
    $field->save();
  }

  /** @var \Drupal\Core\Entity\EntityDisplayRepositoryInterface $entity_display */
  $entity_display = \Drupal::service('entity_display.repository');
  $bundles = ['event', 'location', 'profile', 'article'];
  foreach ($bundles as $bundle) {
    // Form displays.
    $display = $entity_display->getFormDisplay('node', $bundle, 'bulk_edit');
    if (!$display->isNew()) {
      $display->removeComponent('field_comments_mode');
      $display->save();
    }

    $display = $entity_display->getFormDisplay('node', $bundle, 'default');
    if (!$display->isNew()) {
      $display->removeComponent('field_comments_mode');
      $group_administrative = $display->getThirdPartySetting('field_group', 'group_administrative');
      if (is_array($group_administrative) && is_array($group_administrative['children'])) {
        foreach ($group_administrative['children'] as $key => $child) {
          if ($child === 'field_comments_mode') {
            unset($group_administrative['children'][$key]);
            $group_administrative['children'] = array_values($group_administrative['children']);
          }
        }

        $display->setThirdPartySetting('field_group', 'group_administrative', $group_administrative);
      }

      $display->save();
    }

    // View displays.
    $display = $entity_display->getViewDisplay('node', $bundle, 'full');
    if (!$display->isNew()) {
      if ($display instanceof LayoutBuilderEntityViewDisplay && $display->isLayoutBuilderEnabled()) {
        foreach ($display->getSections() as $delta => $section) {
          foreach ($section->getComponents() as $component) {
            if ($component->getUuid() === '48b3e6a3-abb8-452d-8695-1e980c92c4fb') {
              $display->removeSection($delta);
              break 2;
            }
          }
        }
      }
      else {
        $display->removeComponent('field_comments');
        $display->unsetThirdPartySetting('field_group', 'group_comments');
      }

      $display->save();
    }
  }

  $configFactory = \Drupal::configFactory();
  $configFactory->getEditable('auto_entitylabel.settings.node.comment')->delete();
}

/**
 * Implements hook_update_last_removed().
 */
function openculturas_discussions_update_last_removed(): int {
  return 10001;
}

/**
 * Do not filter by langcode to always render comments.
 */
function openculturas_discussions_update_10002(): string {
  $full_config_names = [
    'views.view.related_comments',
  ];
  /** @var \Drupal\config_update\ConfigReverter $configUpdater */
  $configUpdater = \Drupal::service('config_update.config_update');
  /** @var \Drupal\update_helper\UpdateLogger $logger */
  $logger = \Drupal::service('update_helper.logger');
  foreach ($full_config_names as $full_config_name) {
    $config_name = ConfigName::createByFullName($full_config_name);
    if ($configUpdater->revert($config_name->getType(), $config_name->getName())) {
      $logger->info(sprintf('Configuration %s has been successfully reverted.', $full_config_name));
    }
    else {
      $logger->warning(sprintf('Unable to import %s config, because configuration file is not found.', $full_config_name));
    }
  }

  return $logger->output();
}
