<?php

declare(strict_types=1);

/**
 * Implements hook_token_info().
 */
function openculturas_address_links_token_info(): array {
  return [
    'types' => [
      'address' => [
        'name' => t('Address'),
        'description' => t('Address tokens.'),
      ],
      'geofield' => [
        'name' => t('Geofield'),
        'description' => t('Geofield tokens.'),
      ],
    ],
    'tokens' => [
      'address' => [
        'address' => [
          'name' => t('Address'),
          'description' => t('Plaintext address in a single line.'),
        ],
      ],
      'geofield' => [
        'lat' => [
          'name' => t('Latitude'),
          'description' => t('Latitude of the address geofield.'),
        ],
        'lon' => [
          'name' => t('Longitude'),
          'description' => t('Longitude of the address geofield.'),
        ],
        'latlon' => [
          'name' => t('Latitude/longitude'),
          'description' => t('Latitude and longitude of the address geofield, separated by comma.'),
        ],
      ],
    ],
  ];
}

/**
 * Implements hook_tokens().
 */
function openculturas_address_links_tokens(string $type, array $tokens, array $data): array {
  $replacements = [];
  /** @var \Drupal\openculturas_address_links\AddressService $addressService */
  $addressService = \Drupal::service('openculturas_address_links.address_service');
  /** @var array<string, string> $tokens */
  if ($type === 'address') {
    /** @var \Drupal\address\AddressInterface $address */
    $address = $data['address'];
    foreach ($tokens as $name => $original) {
      if ($name === 'address') {
        $replacements[$original] = $addressService->getPlainAddress($address);
      }
    }
  }
  elseif ($type === 'geofield') {
    /** @var object{lat: mixed, lon: mixed, latlon: mixed} $geofield */
    $geofield = $data['geofield'];
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'lat':
          $replacements[$original] = $geofield->lat;
          break;

        case 'lon':
          $replacements[$original] = $geofield->lon;
          break;

        case 'latlon':
          $replacements[$original] = $geofield->latlon;
          break;
      }
    }
  }

  return $replacements;
}
